services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    volumes:
      - ./logstash/pipeline/config.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/config.conf:/usr/share/logstash/config/logstash-sample.conf
      - ./logstash/dummyData/:/usr/share/logstash/dummyData/
    ports:
      - "5044:5044"
